#!/usr/bin/env bash
# bashformer — decoder-only Transformer inference in GNU Bash.
# Runtime contract: Bash builtins only. Notorch is a build/training dependency.

set -u
LC_ALL=C
export LC_ALL
BF_VERSION=0.5.0

bf_die() {
    printf 'bashformer: %s\n' "$*" >&2
    exit 1
}

bf_usage() {
    printf '%s\n' \
        'usage: ./bashformer.sh [options]' \
        '' \
        '  --weights FILE       BFW1 weights (default: weights/bashformer.bfw)' \
        '  --prompt TEXT        prompt (default: The blood was )' \
        '  --tokens N           generated bytes (default: 32)' \
        '  --temperature X      0 = greedy; decimal sampling temperature' \
        '  --seed N             deterministic sampler seed (default: 1)' \
        '  --method             enable the Method field with canonical laws' \
        '  --field on|off       explicitly gate the Method overlay' \
        '  --velocity MODE      raw, nomove, walk, run, or breathe' \
        '  --prophecy N         destiny horizon, 1..64 (default: 7)' \
        '  --destiny X          destiny strength, 0..1' \
        '  --pain X             compress logits toward their mean, 0..1' \
        '  --focus X            attention focus, 0..1' \
        '  --spread X           attention spread, 0..1' \
        '  --entropy-floor X    minimum uncertainty law, 0..1 (default: 0.1)' \
        '  --resonance-ceiling X maximum coherence law, 0..1 (default: 0.95)' \
        '  --debt X             prophecy debt, 0..100 (default: soma or 0)' \
        '  --debt-decay X       per-emitted-token debt decay, 0..1 (default: 0.998)' \
        '  --hebbian            enable live co-occurrence H-term memory' \
        '  --plasticity MODE    flat or debt-gated Hebbian learning (default: flat)' \
        '  --spa                enable Sentence Phonon Attention' \
        '  --spa-alpha X        sentence recency decay, 0..1 (default: 0.85)' \
        '  --spa-strength X     connectedness sharpening, 0..1 (default: 0.30)' \
        '  --spa-history N      retained sentence embeddings, 1..8 (default: 8)' \
        '  --soma FILE          load/save persistent field state (BFSOMA3; reads v1/v2)' \
        '  --learn on|off       permit persistent memory/dynamics mutation (default: on)' \
        '  --next-id            print only the next token id' \
        '  --next-hex           print only the next token byte in hex' \
        '  --generated-only     suppress prompt echo' \
        '  --trace              emit integer stage checksums to stderr' \
        '  --version            print the release version' \
        '  -h, --help           show this help' \
        '' \
        'The inference path invokes no awk, bc, sed, Python, C binary, or shared library.'
}

bf_require_bash() {
    local major=${BASH_VERSINFO[0]:-0} minor=${BASH_VERSINFO[1]:-0}
    (( major > 4 || (major == 4 && minor >= 3) )) || \
        bf_die "GNU Bash >= 4.3 required (found ${BASH_VERSION:-unknown})"
}

bf_script_dir() {
    local src=${BASH_SOURCE[0]} dir old=$PWD
    if [[ $src == */* ]]; then dir=${src%/*}; else dir=.; fi
    builtin cd "$dir" || return 1
    BF_ROOT=$PWD
    builtin cd "$old" || return 1
}

# Loaded model state.
declare -a BF_TENSOR_NAMES=() BF_ID_TO_HEX=()
declare -A BF_HEX_TO_ID=() BF_SEEN_TENSOR=() BF_SEEN_META=()
BF_VOCAB_HEX=''
BF_VALUE_LIMIT=$((1 << 26))
# Range check for a full 24-value record as one arithmetic expansion. A loop of
# 24 checks costs 0.910s per 20k records against 0.429s here; the file is mostly
# full records, so the loop only runs on the short tail one.
BF_RANGE24=''
for _bf_i in {0..23}; do
    BF_RANGE24+="|(vals[$_bf_i]>BF_VALUE_LIMIT)|(vals[$_bf_i]< -BF_VALUE_LIMIT)"
done
BF_RANGE24=${BF_RANGE24#|}
unset _bf_i

bf_parse_int() {
    local s=$1 sign=1 mag value
    [[ $s =~ ^-?(0|[1-9][0-9]*)$ ]] || return 1
    if [[ $s == -* ]]; then sign=-1; mag=${s#-}; else mag=$s; fi
    (( ${#mag} <= 10 )) || return 1
    if (( ${#mag} == 10 )) && [[ $mag > 2147483647 ]]; then return 1; fi
    value=$((10#$mag))
    REPLY=$((sign * value))
}

bf_parse_nonnegative_i64() {
    local s=$1
    [[ $s =~ ^(0|[1-9][0-9]*)$ ]] || return 1
    (( ${#s} <= 19 )) || return 1
    if (( ${#s} == 19 )) && [[ $s > 9223372036854775807 ]]; then return 1; fi
    REPLY=$((10#$s))
    (( REPLY >= 0 ))
}

bf_meta_ready() {
    local key
    for key in QSHIFT VOCAB DIM LAYERS QHEADS KVHEADS HEAD_DIM FFN CTX \
               LUT_STEPS UNK_ID TIE_HEAD ATTN_SCALE_Q EPS_Q2 ROPE_THETA; do
        [[ -v $key ]] || return 1
    done
}


bf_set_meta() {
    local key=$1 value=$2
    case $key in
        QSHIFT|VOCAB|DIM|LAYERS|QHEADS|KVHEADS|HEAD_DIM|FFN|CTX|LUT_STEPS|UNK_ID|TIE_HEAD|ATTN_SCALE_Q|EPS_Q2|ROPE_THETA)
            printf -v "$key" '%s' "$value"
            ;;
        *) bf_die "unknown metadata key: $key" ;;
    esac
}

bf_tensor_expected() {
    local name=$1 layer field
    case $name in
        WTE) REPLY=$((VOCAB * DIM)); return 0 ;;
        HEAD) (( TIE_HEAD == 0 )) || return 1; REPLY=$((VOCAB * DIM)); return 0 ;;
        RMSF) REPLY=$DIM; return 0 ;;
        ROPE_COS|ROPE_SIN) REPLY=$((CTX * (HEAD_DIM / 2))); return 0 ;;
        EXP_NEG|SIGMOID) REPLY=$((16 * LUT_STEPS + 1)); return 0 ;;
    esac
    if [[ $name =~ ^L([0-9]+)_(RMS1|WQ|WK|WV|WO|RMS2|WG|WU|WD)$ ]]; then
        layer=${BASH_REMATCH[1]}; field=${BASH_REMATCH[2]}
        (( layer >= 0 && layer < LAYERS )) || return 1
        case $field in
            RMS1|RMS2) REPLY=$DIM ;;
            WQ|WO) REPLY=$((DIM * DIM)) ;;
            WK|WV) REPLY=$((KVHEADS * HEAD_DIM * DIM)) ;;
            WG|WU) REPLY=$((FFN * DIM)) ;;
            WD) REPLY=$((DIM * FFN)) ;;
        esac
        return 0
    fi
    return 1
}

bf_expect_tensor() {
    local name=$1 expected=$2
    [[ -v $name ]] || bf_die "missing tensor: $name"
    local -n tensor=$name
    (( ${#tensor[@]} == expected )) || \
        bf_die "$name: expected $expected values, got ${#tensor[@]}"
    unset -n tensor
}

bf_validate_metadata() {
    local required l
    for required in QSHIFT VOCAB DIM LAYERS QHEADS KVHEADS HEAD_DIM FFN CTX \
                    LUT_STEPS UNK_ID TIE_HEAD ATTN_SCALE_Q EPS_Q2 ROPE_THETA; do
        [[ -v $required ]] || bf_die "missing metadata: $required"
    done
    (( QSHIFT > 0 && QSHIFT < 24 )) || bf_die 'QSHIFT outside safe range'
    (( VOCAB > 0 && VOCAB <= 512 )) || bf_die 'VOCAB outside safe range'
    (( DIM > 0 && DIM <= 256 )) || bf_die 'DIM outside safe range'
    (( LAYERS > 0 && LAYERS <= 16 )) || bf_die 'LAYERS outside safe range'
    (( QHEADS > 0 && QHEADS <= 64 )) || bf_die 'QHEADS outside safe range'
    (( KVHEADS > 0 && KVHEADS <= QHEADS )) || bf_die 'KVHEADS outside safe range'
    (( HEAD_DIM > 0 && HEAD_DIM <= 128 )) || bf_die 'HEAD_DIM outside safe range'
    (( FFN > 0 && FFN <= 2048 )) || bf_die 'FFN outside safe range'
    (( CTX > 0 && CTX <= 4096 )) || bf_die 'CTX outside safe range'
    (( LUT_STEPS > 0 && LUT_STEPS <= 1024 )) || bf_die 'LUT_STEPS outside safe range'
    (( TIE_HEAD == 0 || TIE_HEAD == 1 )) || bf_die 'TIE_HEAD must be 0 or 1'
    (( ATTN_SCALE_Q > 0 && ATTN_SCALE_Q <= BF_VALUE_LIMIT )) || bf_die 'ATTN_SCALE_Q outside safe range'
    (( EPS_Q2 >= 0 && EPS_Q2 <= BF_VALUE_LIMIT )) || bf_die 'EPS_Q2 outside safe range'
    (( ROPE_THETA > 1 )) || bf_die 'ROPE_THETA must be greater than 1'
    (( DIM == QHEADS * HEAD_DIM )) || bf_die 'DIM != QHEADS * HEAD_DIM'
    (( QHEADS % KVHEADS == 0 )) || bf_die 'QHEADS not divisible by KVHEADS'
    (( HEAD_DIM % 2 == 0 )) || bf_die 'HEAD_DIM must be even for RoPE'
    (( UNK_ID >= 0 && UNK_ID < VOCAB )) || bf_die 'UNK_ID out of range'

    QS=$((1 << QSHIFT))
    QHALF=$((QS >> 1))
    KV_DIM=$((KVHEADS * HEAD_DIM))
    ROPE_PAIRS=$((HEAD_DIM / 2))
    EXP_MAX_INDEX=$((16 * LUT_STEPS))
    SIG_MAX_INDEX=$((16 * LUT_STEPS))
    bf_activation_limit
}

# Largest activation magnitude that keeps every reduction inside signed 64-bit.
# Weights are bounded at load time, activations are not: they are produced by
# matvec and grow through the residual stream. Each stage below is the widest
# product it forms; 2^62 leaves a bit of headroom over the int64 range.
bf_activation_limit() {
    local cap=$((1 << 62)) cols=$DIM best lim
    (( FFN > cols )) && cols=$FFN
    best=$((cap / (cols * BF_VALUE_LIMIT)))                   # matvec: cols * w * x
    bf_isqrt $((cap / DIM)); lim=$REPLY                       # rmsnorm: n * x^2
    (( lim < best )) && best=$lim
    bf_isqrt $((cap / (HEAD_DIM * ATTN_SCALE_Q))); lim=$REPLY # scores: head_dim * q*k * scale
    (( lim < best )) && best=$lim
    lim=$((cap / (CTX * QS)))                                 # value mix: ctx * exp * v
    (( lim < best )) && best=$lim
    lim=$((cap / QS))                                         # rope, swiglu: x * q-constant
    (( lim < best )) && best=$lim
    (( best > 0 )) || bf_die "model geometry leaves no room for 64-bit fixed point"
    BF_ACT_LIMIT=$best
}

# Fail loud when a stage produces a value the integer contract cannot carry.
# Without this the overflow is silent: Bash wraps, C is undefined, and both
# engines agree on the same garbage, so parity never notices.
bf_check_act() {
    local stage=$1
    local -n a=$2
    local i v
    for ((i=0; i<${#a[@]}; i++)); do
        v=${a[i]}
        (( v <= BF_ACT_LIMIT && v >= -BF_ACT_LIMIT )) || {
            unset -n a
            bf_die "$stage: activation $v exceeds the 64-bit fixed-point contract (limit $BF_ACT_LIMIT)"
        }
    done
    unset -n a
}

bf_validate_model() {
    local l
    bf_validate_metadata
    (( ${#BF_VOCAB_HEX} == VOCAB * 2 )) || bf_die 'vocabulary byte table has wrong length'

    bf_expect_tensor WTE $((VOCAB * DIM))
    if (( TIE_HEAD == 0 )); then bf_expect_tensor HEAD $((VOCAB * DIM)); fi
    bf_expect_tensor RMSF "$DIM"
    bf_expect_tensor ROPE_COS $((CTX * ROPE_PAIRS))
    bf_expect_tensor ROPE_SIN $((CTX * ROPE_PAIRS))
    bf_expect_tensor EXP_NEG $((EXP_MAX_INDEX + 1))
    bf_expect_tensor SIGMOID $((SIG_MAX_INDEX + 1))

    for ((l=0; l<LAYERS; l++)); do
        bf_expect_tensor "L${l}_RMS1" "$DIM"
        bf_expect_tensor "L${l}_WQ" $((DIM * DIM))
        bf_expect_tensor "L${l}_WK" $((KV_DIM * DIM))
        bf_expect_tensor "L${l}_WV" $((KV_DIM * DIM))
        bf_expect_tensor "L${l}_WO" $((DIM * DIM))
        bf_expect_tensor "L${l}_RMS2" "$DIM"
        bf_expect_tensor "L${l}_WG" $((FFN * DIM))
        bf_expect_tensor "L${l}_WU" $((FFN * DIM))
        bf_expect_tensor "L${l}_WD" $((DIM * FFN))
    done
}

bf_load_weights() {
    local file=$1 line tag key value name expected payload current='' count=0 extra
    local -a vals=()
    local seen_header=0 seen_vocab=0 seen_end=0 payload_started=0 old_name
    [[ -r $file ]] || bf_die "cannot read weights: $file"

    for old_name in "${BF_TENSOR_NAMES[@]}"; do unset "$old_name"; done
    unset QSHIFT VOCAB DIM LAYERS QHEADS KVHEADS HEAD_DIM FFN CTX LUT_STEPS \
          UNK_ID TIE_HEAD ATTN_SCALE_Q EPS_Q2 ROPE_THETA
    BF_TENSOR_NAMES=()
    BF_SEEN_TENSOR=()
    BF_SEEN_META=()
    BF_VOCAB_HEX=''

    while IFS= read -r line || [[ -n $line ]]; do
        [[ -z $line || ${line:0:1} == '#' ]] && continue
        (( seen_end == 0 )) || bf_die 'data after BFW1 end marker'
        tag=${line%% *}
        case $tag in
            BFW1)
                [[ $line == BFW1 ]] || bf_die 'malformed BFW1 header'
                (( seen_header == 0 )) || bf_die 'duplicate BFW1 header'
                seen_header=1
                ;;
            M)
                (( seen_header == 1 )) || bf_die 'metadata before BFW1 header'
                [[ -z $current ]] || bf_die 'metadata inside tensor'
                (( payload_started == 0 )) || bf_die 'metadata after model payload began'
                read -r _ key value extra <<< "$line"
                [[ $key =~ ^[A-Z][A-Z0-9_]*$ && -z ${extra:-} ]] || \
                    bf_die "bad metadata: $line"
                bf_parse_int "$value" || bf_die "bad metadata integer: $value"
                value=$REPLY
                [[ ! -v BF_SEEN_META[$key] ]] || bf_die "duplicate metadata: $key"
                BF_SEEN_META[$key]=1
                bf_set_meta "$key" "$value"
                ;;
            V)
                (( seen_header == 1 )) || bf_die 'vocabulary before BFW1 header'
                [[ -z $current ]] || bf_die 'vocabulary inside tensor'
                bf_meta_ready || bf_die 'vocabulary before complete metadata'
                bf_validate_metadata
                (( seen_vocab == 0 )) || bf_die 'duplicate vocabulary table'
                BF_VOCAB_HEX=${line#V }
                [[ $BF_VOCAB_HEX =~ ^[0-9a-fA-F]+$ ]] || bf_die 'bad vocabulary hex'
                BF_VOCAB_HEX=${BF_VOCAB_HEX,,}
                seen_vocab=1
                payload_started=1
                ;;
            T)
                (( seen_header == 1 )) || bf_die 'tensor before BFW1 header'
                (( seen_vocab == 1 )) || bf_die 'tensor before vocabulary table'
                [[ -z $current ]] || bf_die "nested tensor after $current"
                read -r _ name expected extra <<< "$line"
                [[ $name =~ ^[A-Z][A-Z0-9_]*$ && -z ${extra:-} ]] || \
                    bf_die "bad tensor header: $line"
                bf_parse_int "$expected" || bf_die "bad tensor count: $expected"
                expected=$REPLY
                (( expected >= 0 )) || bf_die "negative tensor count: $name"
                bf_tensor_expected "$name" || bf_die "unknown tensor: $name"
                (( expected == REPLY )) || bf_die "$name: header says $expected values, architecture requires $REPLY"
                [[ ! -v BF_SEEN_TENSOR[$name] ]] || bf_die "duplicate tensor: $name"
                BF_SEEN_TENSOR[$name]=1
                current=$name
                count=0
                declare -g -a "$name=()"
                BF_TENSOR_NAMES+=("$name")
                payload_started=1
                ;;
            D)
                [[ -n $current ]] || bf_die 'tensor data outside tensor'
                payload=${line#D}
                # One match for the whole record instead of a function call per
                # value: a 9M-parameter model has 9M of them, and the per-value
                # path cost 22.6us each. The pattern still forbids leading zeros,
                # so the values below are safe to hand to arithmetic - that check
                # is what keeps weight data from being read as shell.
                [[ $payload =~ ^([[:space:]]+-?(0|[1-9][0-9]{0,9}))+[[:space:]]*$ ]] || \
                    bf_die "$current contains non-integer data"
                vals=()
                read -r -a vals <<< "$payload"
                local vi
                if (( ${#vals[@]} == 24 )); then
                    (( BF_RANGE24 )) && bf_die "$current contains an unsafe fixed-point value"
                else
                    for ((vi=0; vi<${#vals[@]}; vi++)); do
                        (( vals[vi] >= -BF_VALUE_LIMIT && vals[vi] <= BF_VALUE_LIMIT )) || \
                            bf_die "$current contains unsafe fixed-point value: ${vals[vi]}"
                    done
                fi
                local -n target=$current
                target+=("${vals[@]}")
                count=$((count + ${#vals[@]}))
                (( count <= expected )) || bf_die "$current contains too many values"
                unset -n target
                ;;
            E)
                [[ $line == E ]] || bf_die 'malformed tensor end marker'
                [[ -n $current ]] || bf_die 'tensor end outside tensor'
                (( count == expected )) || bf_die "$current: expected $expected values, got $count"
                current=''
                count=0
                ;;
            Z)
                [[ $line == Z ]] || bf_die 'malformed BFW1 end marker'
                [[ -z $current ]] || bf_die "unterminated tensor: $current"
                seen_end=1
                ;;
            *) bf_die "unknown BFW1 record: $tag" ;;
        esac
    done < "$file"

    (( seen_header == 1 )) || bf_die 'not a BFW1 file'
    (( seen_end == 1 )) || bf_die 'missing BFW1 end marker'
    [[ -z $current ]] || bf_die "unterminated tensor: $current"
    bf_validate_model

    BF_ID_TO_HEX=()
    BF_HEX_TO_ID=()
    local i hx
    local -A seen_byte=()
    for ((i=0; i<VOCAB; i++)); do
        hx=${BF_VOCAB_HEX:i*2:2}
        [[ $hx != 00 ]] || bf_die 'NUL cannot be represented by a Bash string vocabulary'
        [[ ! -v seen_byte[$hx] ]] || bf_die "duplicate vocabulary byte: $hx"
        seen_byte[$hx]=1
        BF_ID_TO_HEX[i]=$hx
        BF_HEX_TO_ID[$hx]=$i
    done
    bf_compile_all
    bf_reset_cache
}

# Compile every matrix the decode path multiplies by. WTE stays an array as
# well: it is the embedding table, read by row, and only its tied-head use is a
# matrix. The raw arrays of the rest are released - keeping both forms would
# double the footprint for no gain.
bf_compile_all() {
    local l name
    for ((l=0; l<LAYERS; l++)); do
        bf_compile_matrix "L${l}_WQ" "$DIM" "$DIM"
        bf_compile_matrix "L${l}_WK" "$KV_DIM" "$DIM"
        bf_compile_matrix "L${l}_WV" "$KV_DIM" "$DIM"
        bf_compile_matrix "L${l}_WO" "$DIM" "$DIM"
        bf_compile_matrix "L${l}_WG" "$FFN" "$DIM"
        bf_compile_matrix "L${l}_WU" "$FFN" "$DIM"
        bf_compile_matrix "L${l}_WD" "$DIM" "$FFN"
        for name in WQ WK WV WO WG WU WD; do unset "L${l}_$name"; done
    done
    if (( TIE_HEAD )); then
        bf_compile_matrix WTE "$VOCAB" "$DIM"
    else
        bf_compile_matrix HEAD "$VOCAB" "$DIM"
        unset HEAD
    fi
}

bf_reset_cache() {
    local l
    for ((l=0; l<LAYERS; l++)); do
        declare -g -a "BF_K_CACHE_${l}=()"
        declare -g -a "BF_V_CACHE_${l}=()"
    done
}

# Signed round-to-nearest for a QSHIFT right shift. Result in REPLY.
bf_qshift() {
    local x=$1
    if (( x >= 0 )); then REPLY=$(((x + QHALF) >> QSHIFT))
    else REPLY=$(( - (((-x) + QHALF) >> QSHIFT) ))
    fi
}

bf_isqrt() {
    local n=$1 x y
    if (( n <= 0 )); then REPLY=0; return; fi
    x=$n
    y=$(((x + 1) / 2))
    while (( y < x )); do
        x=$y
        y=$(((x + n / x) / 2))
    done
    REPLY=$x
}

# A matrix row is compiled once into an arithmetic expression over BF_IN, the
# nameref every matvec binds to its input vector. Bash expands a variable inside
# an arithmetic context as an expression, so no eval is involved and the runtime
# contract holds. This trades one hash lookup per weight for one per row: the
# same arithmetic, 5x less of the interpreter. Zero weights are dropped at
# compile time - they contribute nothing and cost a multiply each token.
bf_compile_matrix() {
    local name=$1 rows=$2 cols=$3
    local -n w=$name
    declare -g -a "${name}_EXPR=()"
    local -n dst="${name}_EXPR"
    local r c base acc v
    for ((r=0; r<rows; r++)); do
        base=$((r * cols)); acc=''
        for ((c=0; c<cols; c++)); do
            v=${w[base+c]}
            (( v == 0 )) && continue
            acc+="+$v*BF_IN[$c]"
        done
        if [[ -z $acc ]]; then dst[r]=0; else dst[r]=${acc#+}; fi
    done
    unset -n w dst
}

bf_matvec() {
    local out_name=$1 w_name=$2 rows=$3 cols=$4 x_name=$5
    local -n out=$out_name BF_IN=$x_name we="${w_name}_EXPR"
    local r e t
    out=()
    for ((r=0; r<rows; r++)); do
        e=${we[r]}
        (( t = e ))
        (( out[r] = t>=0 ? (t+QHALF)>>QSHIFT : -(((-t)+QHALF)>>QSHIFT) ))
    done
    unset -n out BF_IN we
}

bf_rmsnorm() {
    local out_name=$1 x_name=$2 gamma_name=$3 n=$4
    local -n out=$out_name x=$x_name gamma=$gamma_name
    local i sumsq mean rms p
    sumsq=0
    for ((i=0; i<n; i++)); do (( sumsq += x[i] * x[i] )); done
    mean=$((sumsq / n + EPS_Q2))
    bf_isqrt "$mean"
    rms=$REPLY
    (( rms > 0 )) || rms=1
    out=()
    for ((i=0; i<n; i++)); do
        p=$((x[i] * gamma[i]))
        if (( p >= 0 )); then out[i]=$(((p + rms/2) / rms))
        else out[i]=$(( - (((-p) + rms/2) / rms) ))
        fi
    done
    unset -n out x gamma
}

# Llama RoPE: adjacent real/imag lane pairs (0,1), (2,3), ... per head.
bf_rope_inplace() {
    local arr_name=$1 heads=$2 pos=$3
    local -n a=$arr_name
    local h pair i0 i1 ti co si x0 x1 p0 p1
    for ((h=0; h<heads; h++)); do
        for ((pair=0; pair<ROPE_PAIRS; pair++)); do
            i0=$((h * HEAD_DIM + 2 * pair)); i1=$((i0 + 1))
            ti=$((pos * ROPE_PAIRS + pair))
            co=${ROPE_COS[ti]}; si=${ROPE_SIN[ti]}
            x0=${a[i0]}; x1=${a[i1]}
            p0=$((x0 * co - x1 * si)); p1=$((x0 * si + x1 * co))
            bf_qshift "$p0"; a[i0]=$REPLY
            bf_qshift "$p1"; a[i1]=$REPLY
        done
    done
    unset -n a
}

bf_store_kv() {
    local layer=$1 pos=$2 k_name=$3 v_name=$4
    local -n k=$k_name v=$v_name
    local kcn="BF_K_CACHE_${layer}" vcn="BF_V_CACHE_${layer}"
    local -n kc=$kcn vc=$vcn
    local i off=$((pos * KV_DIM))
    for ((i=0; i<KV_DIM; i++)); do kc[off+i]=${k[i]}; vc[off+i]=${v[i]}; done
    unset -n k v kc vc
}

bf_attention() {
    local out_name=$1 q_name=$2 layer=$3 pos=$4
    local -n out=$out_name q=$q_name
    local kcn="BF_K_CACHE_${layer}" vcn="BF_V_CACHE_${layer}"
    local -n kc=$kcn vc=$vcn
    local q_per_kv=$((QHEADS / KVHEADS))
    local h kvh t d qoff koff raw score max diff idx e sumexp num
    local -a scores=() exps=()
    out=()

    for ((h=0; h<QHEADS; h++)); do
        kvh=$((h / q_per_kv)); qoff=$((h * HEAD_DIM))
        max=-9223372036854775807; scores=()
        for ((t=0; t<=pos; t++)); do
            koff=$((t * KV_DIM + kvh * HEAD_DIM)); raw=0
            for ((d=0; d<HEAD_DIM; d++)); do
                (( raw += q[qoff+d] * kc[koff+d] ))
            done
            # raw Q^(2); ATTN_SCALE_Q Q; shift 2Q -> Q.
            local scaled=$((raw * ATTN_SCALE_Q)) half2=$((1 << (2*QSHIFT-1)))
            if (( scaled >= 0 )); then score=$(((scaled + half2) >> (2*QSHIFT)))
            else score=$(( - (((-scaled) + half2) >> (2*QSHIFT)) ))
            fi
            scores[t]=$score
            (( score > max )) && max=$score
        done

        exps=(); sumexp=0
        for ((t=0; t<=pos; t++)); do
            diff=$((max - scores[t]))
            idx=$(((diff * LUT_STEPS + QHALF) >> QSHIFT))
            (( idx < 0 )) && idx=0
            (( idx > EXP_MAX_INDEX )) && idx=$EXP_MAX_INDEX
            e=${EXP_NEG[idx]}; exps[t]=$e; (( sumexp += e ))
        done
        (( sumexp > 0 )) || sumexp=1

        for ((d=0; d<HEAD_DIM; d++)); do
            num=0
            for ((t=0; t<=pos; t++)); do
                koff=$((t * KV_DIM + kvh * HEAD_DIM))
                (( num += exps[t] * vc[koff+d] ))
            done
            if (( num >= 0 )); then out[qoff+d]=$(((num + sumexp/2) / sumexp))
            else out[qoff+d]=$(( - (((-num) + sumexp/2) / sumexp) ))
            fi
        done
    done
    unset -n out q kc vc
}

bf_swiglu() {
    local out_name=$1 gate_name=$2 up_name=$3 n=$4
    local -n out=$out_name gate=$gate_name up=$up_name
    local i x idx sig prod silu
    out=()
    for ((i=0; i<n; i++)); do
        x=${gate[i]}
        idx=$((((x + 8*QS) * LUT_STEPS + QHALF) >> QSHIFT))
        (( idx < 0 )) && idx=0
        (( idx > SIG_MAX_INDEX )) && idx=$SIG_MAX_INDEX
        sig=${SIGMOID[idx]}
        prod=$((x * sig)); bf_qshift "$prod"; silu=$REPLY
        prod=$((silu * up[i])); bf_qshift "$prod"; out[i]=$REPLY
    done
    unset -n out gate up
}

bf_checksum() {
    local name=$1
    local -n a=$name
    local i s=1469598103934665603
    for ((i=0; i<${#a[@]}; i++)); do
        (( s ^= (a[i] + i * 1315423911) ))
        (( s *= 1099511628211 ))
    done
    REPLY=$s
    unset -n a
}

# Global scratch avoids repeated large array destruction in nested local scopes.
declare -a BF_H=() BF_XN=() BF_Q=() BF_K=() BF_VV=() BF_ATTN=() BF_PROJ=()
declare -a BF_GATE=() BF_UP=() BF_ACT=() BF_DOWN=() BF_HF=() BF_LOGITS=()
BF_LAST_NEXT=0
BF_TRACE=0

# Method field. It is opt-in; vanilla inference remains an exact control.
# The formulas are a literal QSHIFT port of ariannamethod.ai's inference field.
BF_FIELD_ENABLED=0
BF_METHOD_VELOCITY=raw
BF_METHOD_VELOCITY_Q=0
BF_METHOD_PROPHECY=7
BF_METHOD_DESTINY_Q=0
BF_METHOD_PAIN_Q=0
BF_METHOD_FOCUS_Q=0
BF_METHOD_SPREAD_Q=0
BF_METHOD_ENTROPY_FLOOR_Q=0
BF_METHOD_RESONANCE_CEILING_Q=0
BF_METHOD_DEBT_Q=0
BF_METHOD_DEBT_DECAY_Q=0
BF_METHOD_LAST_DEBT_Q=0
BF_METHOD_FIELD_STEPS=0
BF_METHOD_RECOVERIES=0
BF_METHOD_RECOVERY_THRESHOLD_Q=0
BF_METHOD_DEBT_CAP_Q=0
BF_METHOD_STATE_LOADED=0
BF_STATE_MUTABLE=1
BF_BASE_TEMP_Q=0
BF_RNG_STATE=1

# Stateful Method memory/dynamics (v0.5). Co-occurrence counts are QSHIFT fixed-point.
declare -A BF_COOC=()
declare -a BF_COOC_RING=()
BF_HEBBIAN_ENABLED=0
BF_HEBBIAN_LEARN=1
BF_COOC_TOTAL=0
BF_SOMA_FILE=''
BF_COOC_CTX=8
BF_COOC_WINDOW=5
BF_COOC_CAP=0

# Debt-gated plasticity. `flat` preserves the v0.3/v0.4 learning law; `debt`
# raises the per-token Hebbian update from 1x toward 2x as prophecy debt grows.
BF_PLASTICITY_MODE=flat
BF_PLASTICITY_UPDATES=0
BF_PLASTICITY_LAST_GAIN_Q=0

# Sentence Phonon Attention (SPA). History contains flattened QSHIFT sentence
# embeddings; current contains token ids for the unfinished sentence.
BF_SPA_ENABLED=0
BF_SPA_ALPHA_Q=0
BF_SPA_STRENGTH_Q=0
BF_SPA_HISTORY_MAX=8
BF_SPA_HISTORY_N=0
BF_SPA_SENTENCES=0
BF_SPA_LAST_CONN_Q=0
BF_SPA_LAST_TEMP_Q=0
BF_SPA_PENDING_BOUNDARY=0
BF_SPA_SCALE_Q=0
declare -a BF_SPA_HISTORY=()
declare -a BF_SPA_CURRENT=()

bf_qmul() {
    local a=$1 b=$2
    bf_qshift "$((a * b))"
}

bf_div_round() {
    local num=$1 den=$2
    (( den > 0 )) || { REPLY=0; return 1; }
    if (( num >= 0 )); then REPLY=$(((num + den/2) / den))
    else REPLY=$(( - (((-num) + den/2) / den) ))
    fi
}

bf_method_defaults() {
    BF_METHOD_VELOCITY=raw
    BF_METHOD_VELOCITY_Q=$QS
    BF_METHOD_DEBT_Q=0
    BF_METHOD_LAST_DEBT_Q=0
    BF_METHOD_FIELD_STEPS=0
    BF_METHOD_RECOVERIES=0
    BF_METHOD_RECOVERY_THRESHOLD_Q=$((5 * QS))
    BF_METHOD_DEBT_CAP_Q=$((100 * QS))
    BF_METHOD_STATE_LOADED=0
    bf_decimal_to_q '0.998' || bf_die 'internal debt-decay default'
    BF_METHOD_DEBT_DECAY_Q=$REPLY
    bf_decimal_to_q '0.1' || bf_die 'internal entropy-floor default'
    BF_METHOD_ENTROPY_FLOOR_Q=$REPLY
    bf_decimal_to_q '0.95' || bf_die 'internal resonance-ceiling default'
    BF_METHOD_RESONANCE_CEILING_Q=$REPLY

    BF_PLASTICITY_MODE=flat
    BF_PLASTICITY_UPDATES=0
    BF_PLASTICITY_LAST_GAIN_Q=$QS
    bf_decimal_to_q '0.85' || bf_die 'internal SPA alpha default'
    BF_SPA_ALPHA_Q=$REPLY
    bf_decimal_to_q '0.30' || bf_die 'internal SPA strength default'
    BF_SPA_STRENGTH_Q=$REPLY
    BF_SPA_HISTORY_MAX=8
    BF_SPA_HISTORY_N=0
    BF_SPA_SENTENCES=0
    BF_SPA_LAST_CONN_Q=0
    BF_SPA_LAST_TEMP_Q=$QS
    BF_SPA_PENDING_BOUNDARY=0
    BF_SPA_HISTORY=()
    BF_SPA_CURRENT=()

    # QSHIFT approximation of 1/sqrt(DIM), computed with the same integer
    # Newton primitive used by RMSNorm. sqrt(D)*Q is the denominator.
    bf_isqrt "$((DIM * QS * QS))"
    local spa_root=$REPLY
    (( spa_root > 0 )) || spa_root=1
    BF_SPA_SCALE_Q=$(((QS * QS + spa_root/2) / spa_root))
}

bf_effective_temp_q() {
    if (( BF_FIELD_ENABLED && BF_BASE_TEMP_Q > 0 )); then
        bf_qmul "$BF_BASE_TEMP_Q" "$BF_METHOD_VELOCITY_Q"
        (( REPLY > 0 )) || REPLY=1
    else
        REPLY=$BF_BASE_TEMP_Q
    fi
}

bf_recompute_greedy() {
    local i
    BF_LAST_NEXT=0
    for ((i=1; i<VOCAB; i++)); do
        (( BF_LOGITS[i] > BF_LOGITS[BF_LAST_NEXT] )) && BF_LAST_NEXT=$i
    done
}

bf_hebbian_clear() {
    BF_COOC=()
    BF_COOC_RING=()
    BF_COOC_TOTAL=0
    BF_COOC_CAP=$((1000000 * QS))
}

bf_plasticity_gain_q() {
    if [[ $BF_PLASTICITY_MODE == debt ]]; then
        local denom=$((BF_METHOD_DEBT_Q + 5 * QS))
        if (( denom > 0 )); then
            REPLY=$((QS + (BF_METHOD_DEBT_Q * QS + denom/2) / denom))
        else
            REPLY=$QS
        fi
    else
        REPLY=$QS
    fi
}

bf_spa_is_boundary() {
    local token=$1 hx
    hx=${BF_ID_TO_HEX[token]:-}
    case $hx in 0a|21|2e|3f) return 0 ;; *) return 1 ;; esac
}

bf_spa_observe_token() {
    local token=$1
    (( BF_FIELD_ENABLED && BF_SPA_ENABLED )) || return 0
    (( token >= 0 && token < VOCAB )) || token=$UNK_ID
    BF_SPA_CURRENT+=("$token")
    (( ${#BF_SPA_CURRENT[@]} <= CTX )) || BF_SPA_CURRENT=("${BF_SPA_CURRENT[@]:1}")
    if bf_spa_is_boundary "$token"; then BF_SPA_PENDING_BOUNDARY=1
    else BF_SPA_PENDING_BOUNDARY=0
    fi
}

# Exponentially weighted mean of token embeddings. The newest token has weight
# 1.0 and each older token is multiplied by SPA_ALPHA. All arithmetic is QSHIFT.
bf_spa_sentence_embedding() {
    local out_name=$1 n=${#BF_SPA_CURRENT[@]} i d token base weight=$QS sumw=0
    local -n out=$out_name
    out=()
    for ((d=0; d<DIM; d++)); do out[d]=0; done
    (( n > 0 )) || { unset -n out; return 1; }
    for ((i=n-1; i>=0; i--)); do
        token=${BF_SPA_CURRENT[i]}; base=$((token * DIM))
        for ((d=0; d<DIM; d++)); do (( out[d] += WTE[base+d] * weight )); done
        (( sumw += weight ))
        bf_qmul "$weight" "$BF_SPA_ALPHA_Q"; weight=$REPLY
    done
    (( sumw > 0 )) || sumw=1
    for ((d=0; d<DIM; d++)); do
        bf_div_round "${out[d]}" "$sumw"; out[d]=$REPLY
    done
    unset -n out
}

bf_spa_connectedness() {
    BF_SPA_LAST_CONN_Q=0
    BF_SPA_LAST_TEMP_Q=$QS
    (( BF_FIELD_ENABLED && BF_SPA_ENABLED && BF_SPA_HISTORY_N > 0 && ${#BF_SPA_CURRENT[@]} > 0 )) || {
        REPLY=0; return 0;
    }
    local -a query=() scores=() exps=()
    bf_spa_sentence_embedding query || { REPLY=0; return 0; }
    local s d off dot scaled score max=-9223372036854775807 diff idx e sumexp=0 maxexp=0
    local half2=$((1 << (2 * QSHIFT - 1)))
    for ((s=0; s<BF_SPA_HISTORY_N; s++)); do
        off=$((s * DIM)); dot=0
        for ((d=0; d<DIM; d++)); do (( dot += query[d] * BF_SPA_HISTORY[off+d] )); done
        scaled=$((dot * BF_SPA_SCALE_Q))
        if (( scaled >= 0 )); then score=$(((scaled + half2) >> (2 * QSHIFT)))
        else score=$(( - (((-scaled) + half2) >> (2 * QSHIFT)) ))
        fi
        scores[s]=$score
        (( score > max )) && max=$score
    done
    for ((s=0; s<BF_SPA_HISTORY_N; s++)); do
        diff=$((max - scores[s]))
        idx=$(((diff * LUT_STEPS + QHALF) >> QSHIFT))
        (( idx < 0 )) && idx=0
        (( idx > EXP_MAX_INDEX )) && idx=$EXP_MAX_INDEX
        e=${EXP_NEG[idx]}; exps[s]=$e; (( sumexp += e )); (( e > maxexp )) && maxexp=$e
    done
    (( sumexp > 0 )) || { REPLY=0; return 0; }
    REPLY=$(((maxexp * QS + sumexp/2) / sumexp))
    (( REPLY < 0 )) && REPLY=0
    (( REPLY > QS )) && REPLY=$QS
    BF_SPA_LAST_CONN_Q=$REPLY
}

# SPA lowers an effective logit temperature by connectedness. This is the
# fixed-point equivalent of logits /= (1 - strength * connectedness).
bf_apply_spa_to_logits() {
    (( BF_FIELD_ENABLED && BF_SPA_ENABLED )) || return 0
    local conn temp_q i product milli_q
    bf_spa_connectedness; conn=$REPLY
    if (( conn > 0 && BF_SPA_STRENGTH_Q > 0 )); then
        bf_qmul "$BF_SPA_STRENGTH_Q" "$conn"; temp_q=$((QS - REPLY))
        milli_q=$(((QS + 500) / 1000)); (( milli_q < 1 )) && milli_q=1
        (( temp_q < milli_q )) && temp_q=$milli_q
        BF_SPA_LAST_TEMP_Q=$temp_q
        for ((i=0; i<VOCAB; i++)); do
            product=$((BF_LOGITS[i] * QS))
            bf_div_round "$product" "$temp_q"; BF_LOGITS[i]=$REPLY
        done
    fi
    if (( BF_TRACE )); then
        printf 'TRACE spa conn=%d temp=%d current=%d history=%d sentences=%d alpha=%d strength=%d\n' \
            "$BF_SPA_LAST_CONN_Q" "$BF_SPA_LAST_TEMP_Q" "${#BF_SPA_CURRENT[@]}" \
            "$BF_SPA_HISTORY_N" "$BF_SPA_SENTENCES" "$BF_SPA_ALPHA_Q" "$BF_SPA_STRENGTH_Q" >&2
    fi
}

bf_spa_commit_if_boundary() {
    (( BF_FIELD_ENABLED && BF_SPA_ENABLED && BF_SPA_PENDING_BOUNDARY )) || return 0
    local -a emb=()
    if (( BF_STATE_MUTABLE )) && bf_spa_sentence_embedding emb; then
        local d drop
        if (( BF_SPA_HISTORY_N >= BF_SPA_HISTORY_MAX )); then
            drop=$DIM
            BF_SPA_HISTORY=("${BF_SPA_HISTORY[@]:drop}")
            ((BF_SPA_HISTORY_N--))
        fi
        for ((d=0; d<DIM; d++)); do BF_SPA_HISTORY+=("${emb[d]}"); done
        ((BF_SPA_HISTORY_N++))
        ((BF_SPA_SENTENCES++))
    fi
    BF_SPA_CURRENT=()
    BF_SPA_PENDING_BOUNDARY=0
}

bf_hebbian_update_edge() {
    local src=$1 dst=$2 delta=$3 key="$1,$2" value
    (( src >= 0 && src < VOCAB && dst >= 0 && dst < VOCAB && delta > 0 )) || return 0
    value=$((${BF_COOC[$key]:-0} + delta))
    (( value > BF_COOC_CAP )) && value=$BF_COOC_CAP
    BF_COOC[$key]=$value
}

# Incremental equivalent of am_ingest_tokens for a stream: each new token forms
# symmetric, distance-weighted edges with the previous five tokens exactly once.
bf_hebbian_ingest_token() {
    local token=$1 n d prev delta base_delta gain
    (( BF_FIELD_ENABLED && BF_HEBBIAN_ENABLED && BF_HEBBIAN_LEARN )) || return 0
    bf_plasticity_gain_q; gain=$REPLY; BF_PLASTICITY_LAST_GAIN_Q=$gain
    n=${#BF_COOC_RING[@]}
    for ((d=1; d<=BF_COOC_WINDOW && d<=n; d++)); do
        prev=${BF_COOC_RING[n-d]}
        base_delta=$(((QS + d/2) / d))
        bf_qmul "$base_delta" "$gain"; delta=$REPLY
        bf_hebbian_update_edge "$token" "$prev" "$delta"
        bf_hebbian_update_edge "$prev" "$token" "$delta"
    done
    ((BF_COOC_TOTAL++))
    [[ $BF_PLASTICITY_MODE != debt ]] || ((BF_PLASTICITY_UPDATES++))
    BF_COOC_RING+=("$token")
    if (( ${#BF_COOC_RING[@]} > BF_COOC_CTX )); then
        BF_COOC_RING=("${BF_COOC_RING[@]:1}")
    fi
    if (( BF_TRACE )) && [[ $BF_PLASTICITY_MODE == debt ]]; then
        printf 'TRACE plasticity token=%d debt=%d gain=%d updates=%d\n' \
            "$token" "$BF_METHOD_DEBT_Q" "$gain" "$BF_PLASTICITY_UPDATES" >&2
    fi
}

# H[i] = sum_ctx cooc[ctx,i] * recency_decay, max-normalized, alpha_H=2.0.
bf_apply_hebbian_to_logits() {
    (( BF_FIELD_ENABLED && BF_HEBBIAN_ENABLED )) || return 0
    local rn=${#BF_COOC_RING[@]} c src denom decay dst key cnt contrib hmax=0 delta
    (( rn > 0 && ${#BF_COOC[@]} > 0 )) || return 0
    local -a h=()
    for ((dst=0; dst<VOCAB; dst++)); do h[dst]=0; done
    for ((c=0; c<rn; c++)); do
        src=${BF_COOC_RING[c]}
        denom=$((rn - c))
        decay=$(((QS + denom/2) / denom))
        for ((dst=0; dst<VOCAB; dst++)); do
            key="$src,$dst"; cnt=${BF_COOC[$key]:-0}
            (( cnt > 0 )) || continue
            contrib=$(((cnt * decay + QHALF) >> QSHIFT))
            (( h[dst] += contrib ))
        done
    done
    for ((dst=0; dst<VOCAB; dst++)); do (( h[dst] > hmax )) && hmax=${h[dst]}; done
    (( hmax > 0 )) || return 0
    for ((dst=0; dst<VOCAB; dst++)); do
        delta=$(((2 * QS * h[dst] + hmax/2) / hmax))
        (( BF_LOGITS[dst] += delta ))
    done
}

bf_soma_load() {
    local file=$1 line tag a b c extra version=0
    local seen_meta_vocab=0 seen_meta_q=0 seen_meta_total=0 seen_ring=0 seen_current=0 seen_end=0
    local seen_debt=0 seen_decay=0 seen_floor=0 seen_ceiling=0
    local seen_velocity=0 seen_steps=0 seen_recoveries=0
    local seen_plasticity=0 seen_plasticity_updates=0 seen_plasticity_gain=0
    local seen_spa_enabled=0 seen_spa_alpha=0 seen_spa_strength=0 seen_spa_conn=0 seen_spa_temp=0
    local seen_spa_history_max=0 seen_spa_history_n=0 seen_spa_sentences=0
    local expected_spa_n=0 spa_records=0
    [[ -e $file ]] || return 0
    [[ -r $file ]] || bf_die "cannot read soma: $file"
    BF_COOC=(); BF_COOC_RING=(); BF_COOC_TOTAL=0
    BF_SPA_HISTORY=(); BF_SPA_CURRENT=(); BF_SPA_HISTORY_N=0; BF_SPA_PENDING_BOUNDARY=0
    while IFS= read -r line || [[ -n $line ]]; do
        [[ -z $line || ${line:0:1} == '#' ]] && continue
        (( seen_end == 0 )) || bf_die 'data after soma end marker'
        read -r tag a b c extra <<< "$line"
        case $tag in
            BFSOMA1|BFSOMA2|BFSOMA3)
                [[ $line == "$tag" && $version == 0 ]] || bf_die 'malformed/duplicate soma header'
                case $tag in BFSOMA1) version=1 ;; BFSOMA2) version=2 ;; BFSOMA3) version=3 ;; esac
                ;;
            M)
                (( version > 0 )) || bf_die 'soma metadata before header'
                [[ -z ${c:-} && -z ${extra:-} ]] || bf_die "bad soma metadata: $line"
                case $a in
                    VOCAB)
                        (( seen_meta_vocab == 0 )) || bf_die 'duplicate soma VOCAB'
                        bf_parse_int "$b" || bf_die 'bad soma VOCAB'
                        (( REPLY == VOCAB )) || bf_die 'soma VOCAB mismatch'; seen_meta_vocab=1 ;;
                    QSHIFT)
                        (( seen_meta_q == 0 )) || bf_die 'duplicate soma QSHIFT'
                        bf_parse_int "$b" || bf_die 'bad soma QSHIFT'
                        (( REPLY == QSHIFT )) || bf_die 'soma QSHIFT mismatch'; seen_meta_q=1 ;;
                    COOC_TOTAL)
                        (( seen_meta_total == 0 )) || bf_die 'duplicate soma COOC_TOTAL'
                        bf_parse_nonnegative_i64 "$b" || bf_die 'bad soma COOC_TOTAL'
                        BF_COOC_TOTAL=$REPLY; seen_meta_total=1 ;;
                    DEBT_Q)
                        (( seen_debt == 0 )) || bf_die 'duplicate soma DEBT_Q'
                        (( version >= 2 )) || bf_die 'BFSOMA1 cannot contain DEBT_Q'
                        bf_parse_int "$b" || bf_die 'bad soma DEBT_Q'
                        (( REPLY >= 0 && REPLY <= BF_METHOD_DEBT_CAP_Q )) || bf_die 'soma DEBT_Q outside safe range'
                        BF_METHOD_DEBT_Q=$REPLY; seen_debt=1 ;;
                    DEBT_DECAY_Q)
                        (( seen_decay == 0 )) || bf_die 'duplicate soma DEBT_DECAY_Q'
                        (( version >= 2 )) || bf_die 'BFSOMA1 cannot contain DEBT_DECAY_Q'
                        bf_parse_int "$b" || bf_die 'bad soma DEBT_DECAY_Q'
                        (( REPLY >= 0 && REPLY <= QS )) || bf_die 'soma DEBT_DECAY_Q outside 0..Q'
                        BF_METHOD_DEBT_DECAY_Q=$REPLY; seen_decay=1 ;;
                    ENTROPY_FLOOR_Q)
                        (( seen_floor == 0 )) || bf_die 'duplicate soma ENTROPY_FLOOR_Q'
                        (( version >= 2 )) || bf_die 'BFSOMA1 cannot contain ENTROPY_FLOOR_Q'
                        bf_parse_int "$b" || bf_die 'bad soma ENTROPY_FLOOR_Q'
                        (( REPLY >= 0 && REPLY <= QS )) || bf_die 'soma ENTROPY_FLOOR_Q outside 0..Q'
                        BF_METHOD_ENTROPY_FLOOR_Q=$REPLY; seen_floor=1 ;;
                    RESONANCE_CEILING_Q)
                        (( seen_ceiling == 0 )) || bf_die 'duplicate soma RESONANCE_CEILING_Q'
                        (( version >= 2 )) || bf_die 'BFSOMA1 cannot contain RESONANCE_CEILING_Q'
                        bf_parse_int "$b" || bf_die 'bad soma RESONANCE_CEILING_Q'
                        (( REPLY >= 0 && REPLY <= QS )) || bf_die 'soma RESONANCE_CEILING_Q outside 0..Q'
                        BF_METHOD_RESONANCE_CEILING_Q=$REPLY; seen_ceiling=1 ;;
                    VELOCITY)
                        (( seen_velocity == 0 )) || bf_die 'duplicate soma VELOCITY'
                        (( version >= 2 )) || bf_die 'BFSOMA1 cannot contain VELOCITY'
                        bf_velocity_q "$b" || bf_die 'bad soma VELOCITY'
                        BF_METHOD_VELOCITY=$b; BF_METHOD_VELOCITY_Q=$REPLY; seen_velocity=1 ;;
                    FIELD_STEPS)
                        (( seen_steps == 0 )) || bf_die 'duplicate soma FIELD_STEPS'
                        (( version >= 2 )) || bf_die 'BFSOMA1 cannot contain FIELD_STEPS'
                        bf_parse_nonnegative_i64 "$b" || bf_die 'bad soma FIELD_STEPS'
                        BF_METHOD_FIELD_STEPS=$REPLY; seen_steps=1 ;;
                    RECOVERIES)
                        (( seen_recoveries == 0 )) || bf_die 'duplicate soma RECOVERIES'
                        (( version >= 2 )) || bf_die 'BFSOMA1 cannot contain RECOVERIES'
                        bf_parse_nonnegative_i64 "$b" || bf_die 'bad soma RECOVERIES'
                        BF_METHOD_RECOVERIES=$REPLY; seen_recoveries=1 ;;
                    PLASTICITY)
                        (( seen_plasticity == 0 )) || bf_die 'duplicate soma PLASTICITY'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain PLASTICITY'
                        case $b in flat|debt) BF_PLASTICITY_MODE=$b ;; *) bf_die 'bad soma PLASTICITY' ;; esac
                        seen_plasticity=1 ;;
                    PLASTICITY_UPDATES)
                        (( seen_plasticity_updates == 0 )) || bf_die 'duplicate soma PLASTICITY_UPDATES'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain PLASTICITY_UPDATES'
                        bf_parse_nonnegative_i64 "$b" || bf_die 'bad soma PLASTICITY_UPDATES'
                        BF_PLASTICITY_UPDATES=$REPLY; seen_plasticity_updates=1 ;;
                    PLASTICITY_LAST_GAIN_Q)
                        (( seen_plasticity_gain == 0 )) || bf_die 'duplicate soma PLASTICITY_LAST_GAIN_Q'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain PLASTICITY_LAST_GAIN_Q'
                        bf_parse_int "$b" || bf_die 'bad soma PLASTICITY_LAST_GAIN_Q'
                        (( REPLY >= QS && REPLY <= 2 * QS )) || bf_die 'soma PLASTICITY_LAST_GAIN_Q outside Q..2Q'
                        BF_PLASTICITY_LAST_GAIN_Q=$REPLY; seen_plasticity_gain=1 ;;
                    SPA_ENABLED)
                        (( seen_spa_enabled == 0 )) || bf_die 'duplicate soma SPA_ENABLED'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_ENABLED'
                        bf_parse_int "$b" || bf_die 'bad soma SPA_ENABLED'
                        (( REPLY == 0 || REPLY == 1 )) || bf_die 'soma SPA_ENABLED must be 0 or 1'
                        BF_SPA_ENABLED=$REPLY; seen_spa_enabled=1 ;;
                    SPA_ALPHA_Q)
                        (( seen_spa_alpha == 0 )) || bf_die 'duplicate soma SPA_ALPHA_Q'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_ALPHA_Q'
                        bf_parse_int "$b" || bf_die 'bad soma SPA_ALPHA_Q'
                        (( REPLY >= 0 && REPLY <= QS )) || bf_die 'soma SPA_ALPHA_Q outside 0..Q'
                        BF_SPA_ALPHA_Q=$REPLY; seen_spa_alpha=1 ;;
                    SPA_STRENGTH_Q)
                        (( seen_spa_strength == 0 )) || bf_die 'duplicate soma SPA_STRENGTH_Q'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_STRENGTH_Q'
                        bf_parse_int "$b" || bf_die 'bad soma SPA_STRENGTH_Q'
                        (( REPLY >= 0 && REPLY <= QS )) || bf_die 'soma SPA_STRENGTH_Q outside 0..Q'
                        BF_SPA_STRENGTH_Q=$REPLY; seen_spa_strength=1 ;;
                    SPA_HISTORY_MAX)
                        (( seen_spa_history_max == 0 )) || bf_die 'duplicate soma SPA_HISTORY_MAX'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_HISTORY_MAX'
                        bf_parse_int "$b" || bf_die 'bad soma SPA_HISTORY_MAX'
                        (( REPLY >= 1 && REPLY <= 8 )) || bf_die 'soma SPA_HISTORY_MAX outside 1..8'
                        BF_SPA_HISTORY_MAX=$REPLY; seen_spa_history_max=1 ;;
                    SPA_HISTORY_N)
                        (( seen_spa_history_n == 0 )) || bf_die 'duplicate soma SPA_HISTORY_N'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_HISTORY_N'
                        bf_parse_int "$b" || bf_die 'bad soma SPA_HISTORY_N'
                        (( REPLY >= 0 && REPLY <= 8 )) || bf_die 'soma SPA_HISTORY_N outside 0..8'
                        expected_spa_n=$REPLY; seen_spa_history_n=1 ;;
                    SPA_SENTENCES)
                        (( seen_spa_sentences == 0 )) || bf_die 'duplicate soma SPA_SENTENCES'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_SENTENCES'
                        bf_parse_nonnegative_i64 "$b" || bf_die 'bad soma SPA_SENTENCES'
                        BF_SPA_SENTENCES=$REPLY; seen_spa_sentences=1 ;;
                    SPA_LAST_CONN_Q)
                        (( seen_spa_conn == 0 )) || bf_die 'duplicate soma SPA_LAST_CONN_Q'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_LAST_CONN_Q'
                        bf_parse_int "$b" || bf_die 'bad soma SPA_LAST_CONN_Q'
                        (( REPLY >= 0 && REPLY <= QS )) || bf_die 'soma SPA_LAST_CONN_Q outside 0..Q'
                        BF_SPA_LAST_CONN_Q=$REPLY; seen_spa_conn=1 ;;
                    SPA_LAST_TEMP_Q)
                        (( seen_spa_temp == 0 )) || bf_die 'duplicate soma SPA_LAST_TEMP_Q'
                        (( version == 3 )) || bf_die 'legacy soma cannot contain SPA_LAST_TEMP_Q'
                        bf_parse_int "$b" || bf_die 'bad soma SPA_LAST_TEMP_Q'
                        (( REPLY >= 1 && REPLY <= QS )) || bf_die 'soma SPA_LAST_TEMP_Q outside 1..Q'
                        BF_SPA_LAST_TEMP_Q=$REPLY; seen_spa_temp=1 ;;
                    *) bf_die "unknown soma metadata: $a" ;;
                esac
                ;;
            E)
                (( version > 0 && seen_meta_vocab && seen_meta_q )) || bf_die 'soma edge before metadata'
                [[ -z ${extra:-} ]] || bf_die "bad soma edge: $line"
                bf_parse_int "$a" || bf_die 'bad soma edge src'; local src=$REPLY
                bf_parse_int "$b" || bf_die 'bad soma edge dst'; local dst=$REPLY
                bf_parse_nonnegative_i64 "$c" || bf_die 'bad soma edge count'; local count=$REPLY
                (( src >= 0 && src < VOCAB && dst >= 0 && dst < VOCAB && count > 0 && count <= BF_COOC_CAP )) || bf_die 'soma edge outside safe range'
                [[ ! -v BF_COOC["$src,$dst"] ]] || bf_die 'duplicate soma edge'
                BF_COOC["$src,$dst"]=$count
                ;;
            R)
                (( version > 0 && seen_meta_vocab && seen_meta_q )) || bf_die 'soma ring before metadata'
                (( seen_ring == 0 )) || bf_die 'duplicate soma ring'
                local -a parts=(); read -r -a parts <<< "$line"
                (( ${#parts[@]} >= 2 )) || bf_die 'bad soma ring'
                bf_parse_int "${parts[1]}" || bf_die 'bad soma ring length'; local rn=$REPLY
                (( rn >= 0 && rn <= BF_COOC_CTX && ${#parts[@]} == rn + 2 )) || bf_die 'bad soma ring length'
                BF_COOC_RING=()
                local ri rid
                for ((ri=0; ri<rn; ri++)); do
                    bf_parse_int "${parts[ri+2]}" || bf_die 'bad soma ring token'; rid=$REPLY
                    (( rid >= 0 && rid < VOCAB )) || bf_die 'soma ring token out of range'
                    BF_COOC_RING+=("$rid")
                done
                seen_ring=1
                ;;
            S)
                (( version == 3 && seen_spa_history_n && seen_spa_history_max )) || bf_die 'SPA embedding before BFSOMA3 metadata'
                local -a sparts=(); read -r -a sparts <<< "$line"
                (( ${#sparts[@]} == DIM + 3 )) || bf_die 'bad SPA embedding width'
                bf_parse_int "${sparts[1]}" || bf_die 'bad SPA embedding index'; local si=$REPLY
                bf_parse_int "${sparts[2]}" || bf_die 'bad SPA embedding dimension'; local sdim=$REPLY
                (( si == spa_records && si < expected_spa_n && sdim == DIM )) || bf_die 'bad SPA embedding index/dimension'
                local sd sv
                for ((sd=0; sd<DIM; sd++)); do
                    bf_parse_int "${sparts[sd+3]}" || bf_die 'bad SPA embedding value'; sv=$REPLY
                    (( sv >= -BF_VALUE_LIMIT && sv <= BF_VALUE_LIMIT )) || bf_die 'SPA embedding outside safe range'
                    BF_SPA_HISTORY+=("$sv")
                done
                ((spa_records++))
                ;;
            C)
                (( version == 3 )) || bf_die 'SPA current sentence in legacy soma'
                (( seen_current == 0 )) || bf_die 'duplicate SPA current sentence'
                local -a cparts=(); read -r -a cparts <<< "$line"
                (( ${#cparts[@]} >= 2 )) || bf_die 'bad SPA current sentence'
                bf_parse_int "${cparts[1]}" || bf_die 'bad SPA current length'; local cn=$REPLY
                (( cn >= 0 && cn <= CTX && ${#cparts[@]} == cn + 2 )) || bf_die 'bad SPA current length'
                BF_SPA_CURRENT=()
                local ci cid
                for ((ci=0; ci<cn; ci++)); do
                    bf_parse_int "${cparts[ci+2]}" || bf_die 'bad SPA current token'; cid=$REPLY
                    (( cid >= 0 && cid < VOCAB )) || bf_die 'SPA current token out of range'
                    BF_SPA_CURRENT+=("$cid")
                done
                seen_current=1
                ;;
            Z)
                [[ $line == Z ]] || bf_die 'malformed soma end marker'
                seen_end=1
                ;;
            *) bf_die "unknown soma record: $tag" ;;
        esac
    done < "$file"
    (( version > 0 && seen_meta_vocab && seen_meta_q && seen_meta_total && seen_ring && seen_end )) || \
        bf_die 'incomplete soma'
    if (( version >= 2 )); then
        (( seen_debt && seen_decay && seen_floor && seen_ceiling && seen_velocity && seen_steps && seen_recoveries )) || \
            bf_die 'incomplete field state'
    fi
    if (( version == 3 )); then
        (( seen_plasticity && seen_plasticity_updates && seen_plasticity_gain && seen_spa_enabled && seen_spa_alpha && \
           seen_spa_strength && seen_spa_conn && seen_spa_temp && seen_spa_history_max && seen_spa_history_n && seen_spa_sentences && seen_current )) || \
            bf_die 'incomplete BFSOMA3 state'
        (( expected_spa_n <= BF_SPA_HISTORY_MAX && spa_records == expected_spa_n )) || bf_die 'SPA history count mismatch'
        BF_SPA_HISTORY_N=$expected_spa_n
        if (( ${#BF_SPA_CURRENT[@]} > 0 )); then
            local last_current=$(( ${#BF_SPA_CURRENT[@]} - 1 ))
            if bf_spa_is_boundary "${BF_SPA_CURRENT[last_current]}"; then BF_SPA_PENDING_BOUNDARY=1; fi
        fi
    fi
    BF_METHOD_STATE_LOADED=$version
}

bf_soma_save() {
    local file=$1 src dst key value s d
    [[ -n $file ]] || return 0
    (( BF_FIELD_ENABLED && BF_STATE_MUTABLE )) || return 0
    {
        printf 'BFSOMA3\n'
        printf 'M VOCAB %d\n' "$VOCAB"
        printf 'M QSHIFT %d\n' "$QSHIFT"
        printf 'M COOC_TOTAL %d\n' "$BF_COOC_TOTAL"
        printf 'M DEBT_Q %d\n' "$BF_METHOD_DEBT_Q"
        printf 'M DEBT_DECAY_Q %d\n' "$BF_METHOD_DEBT_DECAY_Q"
        printf 'M ENTROPY_FLOOR_Q %d\n' "$BF_METHOD_ENTROPY_FLOOR_Q"
        printf 'M RESONANCE_CEILING_Q %d\n' "$BF_METHOD_RESONANCE_CEILING_Q"
        printf 'M VELOCITY %s\n' "$BF_METHOD_VELOCITY"
        printf 'M FIELD_STEPS %d\n' "$BF_METHOD_FIELD_STEPS"
        printf 'M RECOVERIES %d\n' "$BF_METHOD_RECOVERIES"
        printf 'M PLASTICITY %s\n' "$BF_PLASTICITY_MODE"
        printf 'M PLASTICITY_UPDATES %d\n' "$BF_PLASTICITY_UPDATES"
        printf 'M PLASTICITY_LAST_GAIN_Q %d\n' "$BF_PLASTICITY_LAST_GAIN_Q"
        printf 'M SPA_ENABLED %d\n' "$BF_SPA_ENABLED"
        printf 'M SPA_ALPHA_Q %d\n' "$BF_SPA_ALPHA_Q"
        printf 'M SPA_STRENGTH_Q %d\n' "$BF_SPA_STRENGTH_Q"
        printf 'M SPA_HISTORY_MAX %d\n' "$BF_SPA_HISTORY_MAX"
        printf 'M SPA_HISTORY_N %d\n' "$BF_SPA_HISTORY_N"
        printf 'M SPA_SENTENCES %d\n' "$BF_SPA_SENTENCES"
        printf 'M SPA_LAST_CONN_Q %d\n' "$BF_SPA_LAST_CONN_Q"
        printf 'M SPA_LAST_TEMP_Q %d\n' "$BF_SPA_LAST_TEMP_Q"
        for ((src=0; src<VOCAB; src++)); do
            for ((dst=0; dst<VOCAB; dst++)); do
                key="$src,$dst"; value=${BF_COOC[$key]:-0}
                (( value > 0 )) && printf 'E %d %d %d\n' "$src" "$dst" "$value"
            done
        done
        printf 'R %d' "${#BF_COOC_RING[@]}"
        for value in "${BF_COOC_RING[@]}"; do printf ' %d' "$value"; done
        printf '\n'
        for ((s=0; s<BF_SPA_HISTORY_N; s++)); do
            printf 'S %d %d' "$s" "$DIM"
            for ((d=0; d<DIM; d++)); do printf ' %d' "${BF_SPA_HISTORY[s*DIM+d]}"; done
            printf '\n'
        done
        printf 'C %d' "${#BF_SPA_CURRENT[@]}"
        for value in "${BF_SPA_CURRENT[@]}"; do printf ' %d' "$value"; done
        printf '\nZ\n'
    } > "$file" || bf_die "cannot write soma: $file"
}

bf_apply_method_to_logits() {
    (( BF_FIELD_ENABLED )) || return 0
    local i max sum mean diff product suppress prophecy_scale destiny_bias
    local factor scale deviation

    # H term comes first; SPA then sharpens by sentence connectedness before
    # the stateless prophecy/suffering/law operators see the distribution.
    bf_apply_hebbian_to_logits
    bf_apply_spa_to_logits

    # DESTINY + PROPHECY: suppress paths by their distance from the current maximum.
    if (( BF_METHOD_DESTINY_Q > 0 )); then
        prophecy_scale=$((QS + (BF_METHOD_PROPHECY - 7) * ((2 * QS + 50) / 100)))
        (( prophecy_scale < QS / 2 )) && prophecy_scale=$((QS / 2))
        (( prophecy_scale > 2 * QS )) && prophecy_scale=$((2 * QS))
        bf_qmul "$BF_METHOD_DESTINY_Q" "$prophecy_scale"
        destiny_bias=$REPLY
        max=${BF_LOGITS[0]}
        for ((i=1; i<VOCAB; i++)); do
            (( BF_LOGITS[i] > max )) && max=${BF_LOGITS[i]}
        done
        for ((i=0; i<VOCAB; i++)); do
            diff=$((max - BF_LOGITS[i]))
            product=$((diff * destiny_bias))
            # round(diff * destiny_bias * 0.5 / Q), all terms non-negative.
            suppress=$(((product + QS) / (2 * QS)))
            (( BF_LOGITS[i] -= suppress ))
        done
    fi

    # PAIN: compress deviations toward the mean without changing their order.
    if (( BF_METHOD_PAIN_Q > 0 )); then
        sum=0
        for ((i=0; i<VOCAB; i++)); do (( sum += BF_LOGITS[i] )); done
        mean=$((sum / VOCAB))
        factor=$((QS - (BF_METHOD_PAIN_Q + 1) / 2))
        for ((i=0; i<VOCAB; i++)); do
            deviation=$((BF_LOGITS[i] - mean))
            bf_qmul "$deviation" "$factor"
            BF_LOGITS[i]=$((mean + REPLY))
        done
    fi

    # ATTEND_FOCUS / ATTEND_SPREAD: affine sharpening or blurring around the mean.
    scale=$((QS / 2 + BF_METHOD_FOCUS_Q - BF_METHOD_SPREAD_Q))
    (( scale < (QS + 5) / 10 )) && scale=$(((QS + 5) / 10))
    (( scale > 2 * QS )) && scale=$((2 * QS))
    if (( scale != QS )); then
        sum=0
        for ((i=0; i<VOCAB; i++)); do (( sum += BF_LOGITS[i] )); done
        mean=$((sum / VOCAB))
        for ((i=0; i<VOCAB; i++)); do
            deviation=$((BF_LOGITS[i] - mean))
            bf_qmul "$deviation" "$scale"
            BF_LOGITS[i]=$((mean + REPLY))
        done
    fi

    bf_apply_laws_to_logits
}

# Entropy floor and resonance ceiling are a literal fixed-point port of
# ariannamethod.ai's law pass. Both inspect the original top-two gap.
bf_apply_laws_to_logits() {
    (( VOCAB >= 2 )) || return 0
    local i max=${BF_LOGITS[0]} second=-9223372036854775807 gap max_gap reduce
    local ceiling_gap threshold milli_q=$(((QS + 500) / 1000))
    for ((i=1; i<VOCAB; i++)); do
        if (( BF_LOGITS[i] > max )); then
            second=$max; max=${BF_LOGITS[i]}
        elif (( BF_LOGITS[i] > second )); then
            second=${BF_LOGITS[i]}
        fi
    done
    gap=$((max - second))
    if (( gap > 0 && BF_METHOD_ENTROPY_FLOOR_Q > 0 )); then
        max_gap=$((10 * (QS - BF_METHOD_ENTROPY_FLOOR_Q)))
        if (( gap > max_gap )); then
            reduce=$(((gap - max_gap + 1) / 2))
            for ((i=0; i<VOCAB; i++)); do
                (( BF_LOGITS[i] == max )) && (( BF_LOGITS[i] -= reduce ))
            done
        fi
    fi
    if (( BF_METHOD_RESONANCE_CEILING_Q < QS )); then
        ceiling_gap=$((10 * BF_METHOD_RESONANCE_CEILING_Q))
        if (( gap > ceiling_gap )); then
            reduce=$((((gap - ceiling_gap) * 3 + 5) / 10))
            threshold=$((max - milli_q))
            for ((i=0; i<VOCAB; i++)); do
                (( BF_LOGITS[i] >= threshold )) && (( BF_LOGITS[i] -= reduce ))
            done
        fi
    fi
}

bf_compute_choice_debt() {
    local chosen=$1 i max diff denom
    (( chosen >= 0 && chosen < VOCAB )) || { REPLY=0; return 1; }
    max=${BF_LOGITS[0]}
    for ((i=1; i<VOCAB; i++)); do (( BF_LOGITS[i] > max )) && max=${BF_LOGITS[i]}; done
    diff=$((max - BF_LOGITS[chosen]))
    if (( diff <= 0 )); then REPLY=0; return 0; fi
    denom=$((diff + QS))
    REPLY=$(((diff * QS + denom/2) / denom))
}

bf_register_choice_debt() {
    local chosen=$1 add
    BF_METHOD_LAST_DEBT_Q=0
    (( BF_FIELD_ENABLED && BF_STATE_MUTABLE )) || return 0
    bf_compute_choice_debt "$chosen" || return 0
    add=$REPLY; BF_METHOD_LAST_DEBT_Q=$add
    (( BF_METHOD_DEBT_Q += add ))
    (( BF_METHOD_DEBT_Q > BF_METHOD_DEBT_CAP_Q )) && BF_METHOD_DEBT_Q=$BF_METHOD_DEBT_CAP_Q
}

bf_field_step() {
    local chosen=$1 recovered=0 temp_now
    (( BF_FIELD_ENABLED && BF_STATE_MUTABLE )) || return 0
    bf_qmul "$BF_METHOD_DEBT_Q" "$BF_METHOD_DEBT_DECAY_Q"
    BF_METHOD_DEBT_Q=$REPLY
    ((BF_METHOD_FIELD_STEPS++))
    if (( BF_METHOD_DEBT_Q > BF_METHOD_RECOVERY_THRESHOLD_Q )) && [[ $BF_METHOD_VELOCITY != nomove ]]; then
        BF_METHOD_VELOCITY=nomove
        BF_METHOD_VELOCITY_Q=$((QS / 2))
        ((BF_METHOD_RECOVERIES++))
        recovered=1
    fi
    if (( BF_TRACE )); then
        bf_effective_temp_q; temp_now=$REPLY
        printf 'TRACE debt chosen=%d add=%d total=%d velocity=%s temp=%d recovered=%d step=%d recoveries=%d\n' \
            "$chosen" "$BF_METHOD_LAST_DEBT_Q" "$BF_METHOD_DEBT_Q" "$BF_METHOD_VELOCITY" \
            "$temp_now" "$recovered" "$BF_METHOD_FIELD_STEPS" "$BF_METHOD_RECOVERIES" >&2
    fi
}

bf_velocity_q() {
    case $1 in
        raw)     REPLY=$QS ;;
        nomove)  REPLY=$((QS / 2)) ;;
        walk)    REPLY=$(((85 * QS + 50) / 100)) ;;
        run)     REPLY=$(((120 * QS + 50) / 100)) ;;
        breathe) REPLY=$(((60 * QS + 50) / 100)) ;;
        *) return 1 ;;
    esac
}

bf_rng_seed() {
    local seed=$1
    BF_RNG_STATE=$((seed & 0xffffffff))
    (( BF_RNG_STATE != 0 )) || BF_RNG_STATE=1831565813
}

bf_rng_next() {
    local x=$BF_RNG_STATE
    x=$(((x ^ ((x << 13) & 0xffffffff)) & 0xffffffff))
    x=$(((x ^ (x >> 17)) & 0xffffffff))
    x=$(((x ^ ((x << 5) & 0xffffffff)) & 0xffffffff))
    BF_RNG_STATE=$x
    REPLY=$((x & 0x7fffffff))
}

bf_decode_token() {
    local token=$1 pos=$2 l i base ch hsum qsum ksum asum fsum
    (( token >= 0 && token < VOCAB )) || token=$UNK_ID
    (( pos >= 0 && pos < CTX )) || bf_die "context exhausted at $pos (CTX=$CTX)"

    BF_H=(); base=$((token * DIM))
    for ((i=0; i<DIM; i++)); do BF_H[i]=${WTE[base+i]}; done
    bf_check_act embedding BF_H

    for ((l=0; l<LAYERS; l++)); do
        bf_rmsnorm BF_XN BF_H "L${l}_RMS1" "$DIM"
        bf_check_act "L${l} rmsnorm1" BF_XN
        bf_matvec BF_Q "L${l}_WQ" "$DIM" "$DIM" BF_XN
        bf_matvec BF_K "L${l}_WK" "$KV_DIM" "$DIM" BF_XN
        bf_matvec BF_VV "L${l}_WV" "$KV_DIM" "$DIM" BF_XN
        bf_rope_inplace BF_Q "$QHEADS" "$pos"
        bf_rope_inplace BF_K "$KVHEADS" "$pos"
        bf_check_act "L${l} q" BF_Q
        bf_check_act "L${l} k" BF_K
        bf_check_act "L${l} v" BF_VV
        bf_store_kv "$l" "$pos" BF_K BF_VV
        bf_attention BF_ATTN BF_Q "$l" "$pos"
        bf_check_act "L${l} attention" BF_ATTN
        bf_matvec BF_PROJ "L${l}_WO" "$DIM" "$DIM" BF_ATTN
        for ((i=0; i<DIM; i++)); do (( BF_H[i] += BF_PROJ[i] )); done
        bf_check_act "L${l} residual1" BF_H

        bf_rmsnorm BF_XN BF_H "L${l}_RMS2" "$DIM"
        bf_check_act "L${l} rmsnorm2" BF_XN
        bf_matvec BF_GATE "L${l}_WG" "$FFN" "$DIM" BF_XN
        bf_matvec BF_UP "L${l}_WU" "$FFN" "$DIM" BF_XN
        bf_check_act "L${l} gate" BF_GATE
        bf_check_act "L${l} up" BF_UP
        bf_swiglu BF_ACT BF_GATE BF_UP "$FFN"
        bf_check_act "L${l} swiglu" BF_ACT
        bf_matvec BF_DOWN "L${l}_WD" "$DIM" "$FFN" BF_ACT
        for ((i=0; i<DIM; i++)); do (( BF_H[i] += BF_DOWN[i] )); done
        bf_check_act "L${l} residual2" BF_H

        if (( BF_TRACE )); then
            bf_checksum BF_H; hsum=$REPLY
            bf_checksum BF_Q; qsum=$REPLY
            bf_checksum BF_K; ksum=$REPLY
            bf_checksum BF_ATTN; asum=$REPLY
            printf 'TRACE p=%d l=%d h=%d q=%d k=%d a=%d\n' \
                "$pos" "$l" "$hsum" "$qsum" "$ksum" "$asum" >&2
        fi
    done

    bf_rmsnorm BF_HF BF_H RMSF "$DIM"
    bf_check_act "final rmsnorm" BF_HF
    if (( TIE_HEAD )); then bf_matvec BF_LOGITS WTE "$VOCAB" "$DIM" BF_HF
    else bf_matvec BF_LOGITS HEAD "$VOCAB" "$DIM" BF_HF
    fi

    if (( BF_TRACE && BF_FIELD_ENABLED )); then
        bf_checksum BF_LOGITS; fsum=$REPLY
        printf 'TRACE p=%d method_raw=%d\n' "$pos" "$fsum" >&2
    fi
    bf_apply_method_to_logits
    bf_recompute_greedy
    if (( BF_TRACE )); then
        bf_checksum BF_LOGITS; fsum=$REPLY
        printf 'TRACE p=%d logits=%d greedy=%d\n' "$pos" "$fsum" "$BF_LAST_NEXT" >&2
    fi
    bf_spa_commit_if_boundary
}

bf_decimal_to_q() {
    local s=$1 sign=1 whole frac digits scale
    [[ $s == -* ]] && { sign=-1; s=${s#-}; }
    [[ $s =~ ^[0-9]+([.][0-9]+)?$ ]] || return 1
    if [[ $s == *.* ]]; then whole=${s%%.*}; frac=${s#*.}; else whole=$s; frac=''; fi
    (( ${#frac} <= 6 )) || return 1
    (( ${#whole} <= 4 )) || return 1
    digits=${#frac}; scale=1
    while (( digits-- > 0 )); do (( scale *= 10 )); done
    whole=$((10#$whole))
    (( whole <= 1000 )) || return 1
    if [[ -n $frac ]]; then frac=$((10#$frac)); else frac=0; fi
    REPLY=$((sign * (whole * QS + (frac * QS + scale/2) / scale)))
    (( REPLY >= -BF_VALUE_LIMIT && REPLY <= BF_VALUE_LIMIT )) || return 1
}

bf_pick_next() {
    local temp_q=$1 i max diff idx e sumexp=0 r cum=0
    local -a exps=() scaled=()
    if (( temp_q <= 0 )); then REPLY=$BF_LAST_NEXT; return; fi

    max=-9223372036854775807
    for ((i=0; i<VOCAB; i++)); do
        if (( BF_LOGITS[i] >= 0 )); then scaled[i]=$(((BF_LOGITS[i] * QS + temp_q/2) / temp_q))
        else scaled[i]=$(( - (((-BF_LOGITS[i]) * QS + temp_q/2) / temp_q) ))
        fi
        (( scaled[i] > max )) && max=${scaled[i]}
    done
    for ((i=0; i<VOCAB; i++)); do
        diff=$((max - scaled[i]))
        idx=$(((diff * LUT_STEPS + QHALF) >> QSHIFT))
        (( idx > EXP_MAX_INDEX )) && idx=$EXP_MAX_INDEX
        e=${EXP_NEG[idx]}; exps[i]=$e; (( sumexp += e ))
    done
    (( sumexp > 0 )) || { REPLY=$BF_LAST_NEXT; return; }
    bf_rng_next
    r=$((REPLY % sumexp))
    REPLY=$((VOCAB - 1))
    for ((i=0; i<VOCAB; i++)); do
        (( cum += exps[i] ))
        if (( r < cum )); then REPLY=$i; break; fi
    done
}

bf_encode() {
    local text=$1 out_name=$2 i ch ord hx id
    local -n out=$out_name
    out=()
    for ((i=0; i<${#text}; i++)); do
        ch=${text:i:1}
        if [[ $ch == $'\n' ]]; then hx=0a
        else printf -v ord '%d' "'$ch"; printf -v hx '%02x' "$ord"
        fi
        id=${BF_HEX_TO_ID[$hx]:-$UNK_ID}
        out+=("$id")
    done
    unset -n out
}

bf_emit_id() {
    local id=$1 hx=${BF_ID_TO_HEX[id]} byte
    printf -v byte '%b' "\\x$hx"
    printf '%s' "$byte"
}

bf_main() {
    bf_require_bash
    bf_script_dir || bf_die 'cannot resolve script directory'

    local weights="$BF_ROOT/weights/bashformer.bfw" prompt='The blood was '
    local tokens=32 temp='0' seed='1' next_mode='' generated_only=0
    local destiny='0' pain='0' focus='0.5' spread='0'
    local entropy_floor='' resonance_ceiling='' debt='' debt_decay=''
    local velocity='raw' prophecy='7' soma='' learn='on' plasticity='flat'
    local spa_alpha='' spa_strength='' spa_history=''
    local velocity_set=0 floor_set=0 ceiling_set=0 debt_set=0 decay_set=0
    local plasticity_set=0 spa_set=0 spa_alpha_set=0 spa_strength_set=0 spa_history_set=0

    while (( $# )); do
        case $1 in
            --weights) (( $# >= 2 )) || bf_die '--weights needs a path'; weights=$2; shift 2 ;;
            --prompt) (( $# >= 2 )) || bf_die '--prompt needs text'; prompt=$2; shift 2 ;;
            --tokens) (( $# >= 2 )) || bf_die '--tokens needs an integer'; tokens=$2; shift 2 ;;
            --temperature) (( $# >= 2 )) || bf_die '--temperature needs a decimal'; temp=$2; shift 2 ;;
            --seed) (( $# >= 2 )) || bf_die '--seed needs an integer'; seed=$2; shift 2 ;;
            --method) BF_FIELD_ENABLED=1; shift ;;
            --field)
                (( $# >= 2 )) || bf_die '--field needs on or off'
                case $2 in on) BF_FIELD_ENABLED=1 ;; off) BF_FIELD_ENABLED=0 ;; *) bf_die '--field must be on or off' ;; esac
                shift 2 ;;
            --velocity) (( $# >= 2 )) || bf_die '--velocity needs a mode'; velocity=$2; velocity_set=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --prophecy) (( $# >= 2 )) || bf_die '--prophecy needs an integer'; prophecy=$2; BF_FIELD_ENABLED=1; shift 2 ;;
            --destiny) (( $# >= 2 )) || bf_die '--destiny needs a decimal'; destiny=$2; BF_FIELD_ENABLED=1; shift 2 ;;
            --pain) (( $# >= 2 )) || bf_die '--pain needs a decimal'; pain=$2; BF_FIELD_ENABLED=1; shift 2 ;;
            --focus) (( $# >= 2 )) || bf_die '--focus needs a decimal'; focus=$2; BF_FIELD_ENABLED=1; shift 2 ;;
            --spread) (( $# >= 2 )) || bf_die '--spread needs a decimal'; spread=$2; BF_FIELD_ENABLED=1; shift 2 ;;
            --entropy-floor) (( $# >= 2 )) || bf_die '--entropy-floor needs a decimal'; entropy_floor=$2; floor_set=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --resonance-ceiling) (( $# >= 2 )) || bf_die '--resonance-ceiling needs a decimal'; resonance_ceiling=$2; ceiling_set=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --debt) (( $# >= 2 )) || bf_die '--debt needs a decimal'; debt=$2; debt_set=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --debt-decay) (( $# >= 2 )) || bf_die '--debt-decay needs a decimal'; debt_decay=$2; decay_set=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --hebbian) BF_HEBBIAN_ENABLED=1; BF_FIELD_ENABLED=1; shift ;;
            --plasticity) (( $# >= 2 )) || bf_die '--plasticity needs flat or debt'; plasticity=$2; plasticity_set=1; BF_HEBBIAN_ENABLED=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --spa) BF_SPA_ENABLED=1; spa_set=1; BF_FIELD_ENABLED=1; shift ;;
            --spa-alpha) (( $# >= 2 )) || bf_die '--spa-alpha needs a decimal'; spa_alpha=$2; spa_alpha_set=1; spa_set=1; BF_SPA_ENABLED=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --spa-strength) (( $# >= 2 )) || bf_die '--spa-strength needs a decimal'; spa_strength=$2; spa_strength_set=1; spa_set=1; BF_SPA_ENABLED=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --spa-history) (( $# >= 2 )) || bf_die '--spa-history needs an integer'; spa_history=$2; spa_history_set=1; spa_set=1; BF_SPA_ENABLED=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --soma) (( $# >= 2 )) || bf_die '--soma needs a path'; soma=$2; BF_HEBBIAN_ENABLED=1; BF_FIELD_ENABLED=1; shift 2 ;;
            --learn) (( $# >= 2 )) || bf_die '--learn needs on or off'; learn=$2; shift 2 ;;
            --next-id) next_mode=id; shift ;;
            --next-hex) next_mode=hex; shift ;;
            --generated-only) generated_only=1; shift ;;
            --trace) BF_TRACE=1; shift ;;
            --version) printf 'bashformer %s\n' "$BF_VERSION"; return 0 ;;
            -h|--help) bf_usage; return 0 ;;
            *) bf_die "unknown option: $1" ;;
        esac
    done

    bf_parse_int "$tokens" || bf_die '--tokens must be a canonical non-negative integer'
    tokens=$REPLY; (( tokens >= 0 )) || bf_die '--tokens must be non-negative'
    bf_parse_int "$seed" || bf_die '--seed must be a canonical non-negative integer'
    seed=$REPLY; (( seed >= 0 )) || bf_die '--seed must be non-negative'
    bf_parse_int "$prophecy" || bf_die '--prophecy must be a canonical integer'
    BF_METHOD_PROPHECY=$REPLY
    (( BF_METHOD_PROPHECY >= 1 && BF_METHOD_PROPHECY <= 64 )) || bf_die '--prophecy must be in 1..64'

    bf_load_weights "$weights"
    bf_hebbian_clear
    bf_method_defaults
    case $learn in
        on) BF_HEBBIAN_LEARN=1; BF_STATE_MUTABLE=1 ;;
        off) BF_HEBBIAN_LEARN=0; BF_STATE_MUTABLE=0 ;;
        *) bf_die '--learn must be on or off' ;;
    esac
    BF_SOMA_FILE=$soma
    [[ -z $BF_SOMA_FILE ]] || bf_soma_load "$BF_SOMA_FILE"
    (( spa_set )) && BF_SPA_ENABLED=1

    bf_decimal_to_q "$temp" || bf_die 'invalid --temperature'
    BF_BASE_TEMP_Q=$REPLY
    (( BF_BASE_TEMP_Q >= 0 )) || bf_die '--temperature must be non-negative'
    bf_decimal_to_q "$destiny" || bf_die 'invalid --destiny'; BF_METHOD_DESTINY_Q=$REPLY
    bf_decimal_to_q "$pain" || bf_die 'invalid --pain'; BF_METHOD_PAIN_Q=$REPLY
    bf_decimal_to_q "$focus" || bf_die 'invalid --focus'; BF_METHOD_FOCUS_Q=$REPLY
    bf_decimal_to_q "$spread" || bf_die 'invalid --spread'; BF_METHOD_SPREAD_Q=$REPLY
    (( BF_METHOD_DESTINY_Q >= 0 && BF_METHOD_DESTINY_Q <= QS )) || bf_die '--destiny must be in 0..1'
    (( BF_METHOD_PAIN_Q >= 0 && BF_METHOD_PAIN_Q <= QS )) || bf_die '--pain must be in 0..1'
    (( BF_METHOD_FOCUS_Q >= 0 && BF_METHOD_FOCUS_Q <= QS )) || bf_die '--focus must be in 0..1'
    (( BF_METHOD_SPREAD_Q >= 0 && BF_METHOD_SPREAD_Q <= QS )) || bf_die '--spread must be in 0..1'

    if (( velocity_set )); then
        bf_velocity_q "$velocity" || bf_die '--velocity must be raw, nomove, walk, run, or breathe'
        BF_METHOD_VELOCITY=$velocity; BF_METHOD_VELOCITY_Q=$REPLY
    fi
    if (( debt_set )); then
        bf_decimal_to_q "$debt" || bf_die 'invalid --debt'
        (( REPLY >= 0 && REPLY <= BF_METHOD_DEBT_CAP_Q )) || bf_die '--debt must be in 0..100'
        BF_METHOD_DEBT_Q=$REPLY
    fi
    if (( decay_set )); then
        bf_decimal_to_q "$debt_decay" || bf_die 'invalid --debt-decay'
        (( REPLY >= 0 && REPLY <= QS )) || bf_die '--debt-decay must be in 0..1'
        BF_METHOD_DEBT_DECAY_Q=$REPLY
    fi
    if (( floor_set )); then
        bf_decimal_to_q "$entropy_floor" || bf_die 'invalid --entropy-floor'
        (( REPLY >= 0 && REPLY <= QS )) || bf_die '--entropy-floor must be in 0..1'
        BF_METHOD_ENTROPY_FLOOR_Q=$REPLY
    fi
    if (( ceiling_set )); then
        bf_decimal_to_q "$resonance_ceiling" || bf_die 'invalid --resonance-ceiling'
        (( REPLY >= 0 && REPLY <= QS )) || bf_die '--resonance-ceiling must be in 0..1'
        BF_METHOD_RESONANCE_CEILING_Q=$REPLY
    fi
    if (( plasticity_set )); then
        case $plasticity in flat|debt) BF_PLASTICITY_MODE=$plasticity ;; *) bf_die '--plasticity must be flat or debt' ;; esac
    fi
    if (( spa_alpha_set )); then
        bf_decimal_to_q "$spa_alpha" || bf_die 'invalid --spa-alpha'
        (( REPLY >= 0 && REPLY <= QS )) || bf_die '--spa-alpha must be in 0..1'
        BF_SPA_ALPHA_Q=$REPLY
    fi
    if (( spa_strength_set )); then
        bf_decimal_to_q "$spa_strength" || bf_die 'invalid --spa-strength'
        (( REPLY >= 0 && REPLY <= QS )) || bf_die '--spa-strength must be in 0..1'
        BF_SPA_STRENGTH_Q=$REPLY
    fi
    if (( spa_history_set )); then
        bf_parse_int "$spa_history" || bf_die '--spa-history must be a canonical integer'
        (( REPLY >= 1 && REPLY <= 8 )) || bf_die '--spa-history must be in 1..8'
        BF_SPA_HISTORY_MAX=$REPLY
        while (( BF_SPA_HISTORY_N > BF_SPA_HISTORY_MAX )); do
            BF_SPA_HISTORY=("${BF_SPA_HISTORY[@]:DIM}")
            ((BF_SPA_HISTORY_N--))
        done
    fi

    bf_rng_seed "$seed"
    if (( BF_TRACE && BF_FIELD_ENABLED )); then
        local initial_temp_q
        bf_effective_temp_q; initial_temp_q=$REPLY
        printf 'TRACE method velocity=%s base_temp=%d temp=%d prophecy=%d destiny=%d pain=%d focus=%d spread=%d floor=%d ceiling=%d debt=%d decay=%d hebbian=%d edges=%d plasticity=%s gain=%d updates=%d spa=%d alpha=%d strength=%d conn=%d history=%d current=%d sentences=%d steps=%d recoveries=%d soma=%d\n' \
            "$BF_METHOD_VELOCITY" "$BF_BASE_TEMP_Q" "$initial_temp_q" "$BF_METHOD_PROPHECY" \
            "$BF_METHOD_DESTINY_Q" "$BF_METHOD_PAIN_Q" "$BF_METHOD_FOCUS_Q" "$BF_METHOD_SPREAD_Q" \
            "$BF_METHOD_ENTROPY_FLOOR_Q" "$BF_METHOD_RESONANCE_CEILING_Q" "$BF_METHOD_DEBT_Q" \
            "$BF_METHOD_DEBT_DECAY_Q" "$BF_HEBBIAN_ENABLED" "${#BF_COOC[@]}" "$BF_PLASTICITY_MODE" \
            "$BF_PLASTICITY_LAST_GAIN_Q" "$BF_PLASTICITY_UPDATES" "$BF_SPA_ENABLED" "$BF_SPA_ALPHA_Q" \
            "$BF_SPA_STRENGTH_Q" "$BF_SPA_LAST_CONN_Q" "$BF_SPA_HISTORY_N" "${#BF_SPA_CURRENT[@]}" \
            "$BF_SPA_SENTENCES" "$BF_METHOD_FIELD_STEPS" "$BF_METHOD_RECOVERIES" "$BF_METHOD_STATE_LOADED" >&2
    fi

    local -a prompt_ids=()
    local id pos=0 step
    bf_encode "$prompt" prompt_ids
    (( ${#prompt_ids[@]} > 0 )) || prompt_ids=("$UNK_ID")
    local needed=$tokens
    [[ -n $next_mode ]] && needed=1
    (( ${#prompt_ids[@]} + needed <= CTX )) || \
        bf_die "prompt (${#prompt_ids[@]}) + generation ($needed) exceeds CTX=$CTX"

    for id in "${prompt_ids[@]}"; do
        bf_spa_commit_if_boundary
        bf_spa_observe_token "$id"
        bf_hebbian_ingest_token "$id"
        bf_decode_token "$id" "$pos"
        ((pos++))
    done

    if [[ $next_mode == id ]]; then
        printf '%d\n' "$BF_LAST_NEXT"
        bf_spa_commit_if_boundary
        [[ -z $BF_SOMA_FILE ]] || bf_soma_save "$BF_SOMA_FILE"
        return
    elif [[ $next_mode == hex ]]; then
        printf '%s\n' "${BF_ID_TO_HEX[BF_LAST_NEXT]}"
        bf_spa_commit_if_boundary
        [[ -z $BF_SOMA_FILE ]] || bf_soma_save "$BF_SOMA_FILE"
        return
    fi

    (( generated_only )) || printf '%s' "$prompt"
    local effective_temp_q
    for ((step=0; step<tokens; step++)); do
        bf_effective_temp_q; effective_temp_q=$REPLY
        bf_pick_next "$effective_temp_q"; id=$REPLY
        bf_register_choice_debt "$id"
        bf_field_step "$id"
        bf_emit_id "$id"
        bf_spa_commit_if_boundary
        bf_spa_observe_token "$id"
        bf_hebbian_ingest_token "$id"
        if (( step + 1 < tokens )); then
            bf_decode_token "$id" "$pos"
            ((pos++))
        fi
    done
    bf_spa_commit_if_boundary
    printf '\n'
    [[ -z $BF_SOMA_FILE ]] || bf_soma_save "$BF_SOMA_FILE"
}

bf_main "$@"
